### ISSUE TITLE
Chopsticks crash

### ISSUE THREAD

**Issue by qiweiii** [AcalaNetwork/chopsticks#426]
```
023-10-08 15:32:31        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
2023-10-08 15:32:42        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
2023-10-08 15:32:43        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
/root/chopsticks/executor/node/chopsticks_executor.js:229
    wasm.wasm_bindgen__convert__closures__invoke1_mut__h00ad679102bae03c(arg0, arg1, addHeapObject(arg2));
         ^
RuntimeError: unreachable
    at wasm://wasm/00990256:wasm-function[680]:0x12d4f4
    at wasm://wasm/00990256:wasm-function[73]:0x65589
    at wasm://wasm/00990256:wasm-function[100]:0xbc6d7
    at wasm://wasm/00990256:wasm-function[128]:0xce167
    at wasm://wasm/00990256:wasm-function[354]:0x113a06
    at wasm://wasm/00990256:wasm-function[941]:0x139b7f
    at __wbg_adapter_46 (/root/chopsticks/executor/node/chopsticks_executor.js:229:10)
    at real (/root/chopsticks/executor/node/chopsticks_executor.js:214:20)
```

config:

```yml
endpoint: wss://karura-rpc-2.aca-api.network/ws
mock-signature-host: true
block: 5370999
db: ./karura.sqlite
resume: true
wasm-override: /root/configs/karura-2220.wasm

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Tokens:
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: KUSD
        - free: 1000000000000000
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: KSM
        - free: '10000000000000000000'
```

wasm:
[karura-2220.wasm.zip](https://github.com/AcalaNetwork/chopsticks/files/12840143/karura-2220.wasm.zip)
