### ISSUE TITLE
Getting Method not found: chain_getHead from a subsquid indexer

### ISSUE THREAD

**Issue by Tbaut** [AcalaNetwork/chopsticks#434]
Hey there,

I'm forking Rococo and I'd like to run a Subsquid indexer along side Chopsticks.

Running Chopsticks with 
```yml
endpoint: wss://rococo-rpc.polkadot.io
mock-signature-host: true
block: 7437969
db: ./db.sqlite

import-storage:
  System:
    Account:
      - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: '10000000000000000000'
  Council:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
  PhragmenElection:
    Members:
      - who: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        stake: 1000000000000
        deposit: 1000000000000
  TechnicalCommittee:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
  TechnicalMembership:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
```

When I run the indexer pointing at the ws://localhost:8000 I get the following:

> Error handling request: ResponseError: Method not found: chain_getHead 'ResponseError: Method not found: chain_getHead

This is a method that exists on public RPCs:
```bash
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "chain_getHead"}' https://rococo-rpc.polkadot.io
# {"jsonrpc":"2.0","result":"0xc7b638d962eab30042ac50f94c57ebe342ec34db68588c50ac6905054b7dd134","id":1}
```
