### ISSUE TITLE
Unable to map [u8; 32] to a lookup index

### ISSUE THREAD

**Issue by xlc** [AcalaNetwork/chopsticks#550]
got this log with `dev_runBlock`, most likely due to 

https://github.com/AcalaNetwork/chopsticks/blob/eb369abdf12c3e4254157934b2314b27ecf578fa/packages/core/src/utils/well-known-keys.ts#L32

need to check why it is logging this, what's the impact, and see if we can workaround it

**Comment by ermalkaleci** [comment]
has to nothing to do we chopsticks. this happens after you upgrade polkadot/api to 10.11.1 which adds this type https://github.com/polkadot-js/api/commit/d9d0d7b0c8f15495362c82d1023dbf7c8d686864

**Comment by xlc** [comment]
oh interesting. still need to figure out if that log means something is broken or not

**Comment by Tbaut** [comment]
Got this as well with the following config.
```
endpoint: wss://kusama-rpc.polkadot.io
mock-signature-host: true
block: 20487320
db: ./db.sqlite

import-storage:
  System:
    Account:
      - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: '10000000000000000000'
      - - - 5DqVySMC366P8NRjdyp948TJj64hAvg17eaiEn4ZbuKCNZHc
        - providers: 1
          data:
            free: '10000000000000000000'
      - - - 5HKy3cW562kw9zXWQFtMWGqhNYgjLZGntUeYhNFsYcEKqjbc
        - providers: 1
          data:
            free: '10000000000000000000'
  Council:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
  PhragmenElection:
    Members:
      - who: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        stake: 1000000000000
        deposit: 1000000000000
  TechnicalCommittee:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
  TechnicalMembership:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]

```

Also this prints:
```
Error: Cannot find pallet Council
    at objectToStorageItems (/home/thib/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/utils/set-storage.js:20:28)
    at setStorage (/home/thib/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/utils/set-storage.js:70:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async overrideStorage (/home/thib/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/utils/override.js:39:23)
    at async setupContext (/home/thib/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/context.js:142:5)
    at async setupWithServer (/home/thib/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/setup-with-server.js:16:21)
    at async Object.handler (/home/thib/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/cli.js:56:5)

```
