### ISSUE TITLE
Mismatch between configuration and runtime return for u32 storage item

### ISSUE THREAD

**Issue by laurogripa** [AcalaNetwork/chopsticks#605]
I'm trying to change the value of this storage item:
https://github.com/paritytech/substrate/blob/308e6464204d855f18ad0bfd931148cdb2b5dfea/frame/society/src/lib.rs#L683-L685

This is my storage section in the configuration file:
```
  Society:
    $removePrefix:
      - Bids
      - Candidates
      - Members
      - MemberCount
    Bids:
      - who: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
        kind:
          Deposit: 1
        value: 299000000000000
    Candidates:
      -
        -
          - 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty # Bob
        - round: 2
          kind:
            Deposit: 33333333000
          bid: 500000000000000
          tally:
            approvals: 1
            rejections: 0
          skepticStruck: false
    Members:
      -
        -
          - 5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw # Eve
        - rank: 0
          strikes: 5
          index: 0
      -
        -
          - 5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL # Ferdie
        - rank: 1
          strikes: 0
          index: 1
    MemberCount: 2
```

Everything works completely fine, except for the MemberCount, it's yielding `33554432` instead of `2`.
Seems like a binary conversion error, or am I doing something wrong? Any suggestions?

EDIT: adding screenshot to complement the information

![image](https://github.com/AcalaNetwork/chopsticks/assets/6154932/ab5c32b3-f9b0-468f-a052-b359514455e7)
