### ISSUE TITLE
Missing `paraInherent` data from block

### ISSUE THREAD

**Issue by NachoPal** [AcalaNetwork/chopsticks#621]
I am trying to run a network providing chain_spec `genesis` files with the `local` (`kusama-local`, `asset-hub-kusama-local`) implementation.

The config files look something like this:
```yaml
mock-signature-host: true
block: ${env.KUSAMA_BLOCK_NUMBER}
db: ./db.sqlite
port: 8000
runtime-log-level: 5
genesis: ./config/chopsticks/kusama/chain-spec-v1.0.0.json
```
```yaml
mock-signature-host: true
block: ${env.STATEMINE_BLOCK_NUMBER}
db: ./db.sqlite
port: 8001
runtime-log-level: 5
genesis: ./config/chopsticks/asset-hub-kusama/chain-spec-v1.0.0.json
```

And running the command:
```
chopsticks xcm -r config/chopsticks/kusama/config.yml -p config/chopsticks/asset-hub-kusama/config.yml
```

However I am getting the following error:
```
.../@acala-network/chopsticks-core/dist/cjs/blockchain/inherent/para-enter.js:24
            throw new Error('Missing paraInherent data from block');
                  ^

Error: Missing paraInherent data from block
    at ParaInherentEnter.createInherents (.../@acala-network/chopsticks-core/dist/cjs/blockchain/inherent/para-enter.js:24:19)
    at async Promise.all (index 1)
    at async InherentProviders.createInherents (/Users/nacho/Desktop/PARITY/Repos/parachains-integration-tests/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/inherent/index.js:91:23)
    at async TxPool.buildBlock (/Users/nacho/Desktop/PARITY/Repos/parachains-integration-tests/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/txpool.js:312:23)
    at async TxPool.buildBlockIfNeeded (/Users/nacho/Desktop/PARITY/Repos/parachains-integration-tests/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/txpool.js:295:9)
```

**Comment by NachoPal** [comment]
https://github.com/AcalaNetwork/chopsticks/issues/616#issuecomment-1875431775

**Comment by ermalkaleci** [comment]
@NachoPal can you upload genesis file so I don't have to go through building process?

**Comment by NachoPal** [comment]
[chain-spec-v1.0.0.json](https://github.com/AcalaNetwork/chopsticks/files/13858625/chain-spec-v1.0.0.json)
[chain-spec-v1.0.0.json](https://github.com/AcalaNetwork/chopsticks/files/13858628/chain-spec-v1.0.0.json)

**Comment by NachoPal** [comment]
I tried the fix but I am getting this error:
```
TypeError: Cannot read properties of undefined (reading 'downwardMessageQueues')
    at connectDownward (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/packages/core/src/xcm/downward.ts:8:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async connectVertical (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/packages/core/src/xcm/index.ts:10:5)
    at async Object.handler (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/packages/chopsticks/src/cli.ts:43:13)
```

It seems the RelayChain's wasm is replaced by the Parachain's one somewhere, that is why it doesn't find the `dmp` pallet.
I can not find where it happens and I almost sure I am not using genesis files with the same runtime.

For genesis I tried what I had in my local and also:
```yaml
genesis: https://raw.githubusercontent.com/AcalaNetwork/chopsticks/d7b476eb44f14e8e88e39b2f263d9ccffe330c4f/packages/e2e/blobs/kusama.json
```
and
```yaml
genesis: https://raw.githubusercontent.com/AcalaNetwork/chopsticks/d7b476eb44f14e8e88e39b2f263d9ccffe330c4f/packages/e2e/blobs/asset-hub-kusama.json
```

Did it work for you?

**Comment by ermalkaleci** [comment]
@NachoPal Hmmm, remove db. Because they're both genesis with same block hash it will mess caching. Something to be addressed.

**Comment by ermalkaleci** [comment]
just tried pjs and it seems I can't transfer unless I built the first block empty, need to investigate.
Also keep in minding that starting from genesis you won't have any parachain setup, so you'll need to modify storage

**Comment by NachoPal** [comment]
> you won't have any parachain setup

What setup you are referring to?

**Comment by ermalkaleci** [comment]
you will have only genesis state, no asset registered, etc

**Comment by NachoPal** [comment]
> you will have only genesis state, no asset registered, etc

Yeah, that's totally fine

**Comment by NachoPal** [comment]
> Hmmm, remove db. Because they're both genesis with same block hash it will mess caching. Something to be addressed.

This did not work, still getting the same error

**Comment by NachoPal** [comment]
> I did try and it works. what's the error?

The error is the same:
```
TypeError: Cannot read properties of undefined (reading 'downwardMessageQueues')
    at connectDownward (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/packages/core/src/xcm/downward.ts:8:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async connectVertical (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/packages/core/src/xcm/index.ts:10:5)
    at async Object.handler (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/packages/chopsticks/src/cli.ts:43:13)
```

Steps:
1. I remove `db.sqlite`, `db.sqlite-shm`, `db.sqlite-wal`
2. `yarn start xcm -r <path_to_kusama_config> -p <path_to_asset_hub_kusama_config>`

Config files:
- Kusama:
```yaml
mock-signature-host: true
block: ${env.KUSAMA_BLOCK_NUMBER}
db: ./db.sqlite
port: 8000
runtime-log-level: 5
genesis: https://raw.githubusercontent.com/AcalaNetwork/chopsticks/d7b476eb44f14e8e88e39b2f263d9ccffe330c4f/packages/e2e/blobs/kusama.json
```
- AssetHubKusama
```yaml
mock-signature-host: true
block: ${env.STATEMINE_BLOCK_NUMBER}
db: ./db.sqlite
port: 8001
runtime-log-level: 4
genesis: https://raw.githubusercontent.com/AcalaNetwork/chopsticks/d7b476eb44f14e8e88e39b2f263d9ccffe330c4f/packages/e2e/blobs/asset-hub-kusama.json
```

I am up to date with `master`
