### ISSUE TITLE
HRMP not working for genesis mode after opening channels

### ISSUE THREAD

**Issue by NachoPal** [AcalaNetwork/chopsticks#634]
I tried to send HRMP messages after opening the channels in the Relay Chain, however it seems not to work.

I've been digging and `hrmpIngressChannelIndexKey` and `hrmpEgressChannelIndexKey` are returned empty even though they have a value after opening the channels.

In addition, in case that's solved, I think it will still fail because I couldn't find anywhere Parachain's `RelevantMessagingState` is updated as part of `SetValidationData`: https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/pallets/parachain-system/src/lib.rs#L627

**Comment by ermalkaleci** [comment]
Please post more details, like genesis and transaction. I will help me a lot

**Comment by ermalkaleci** [comment]
btw hrmp doesn't go through relaychain. each parachain intercepts its messages

**Comment by ermalkaleci** [comment]
now that I am thinking. This will require faking the ingress/egress channel to make it work for genesis

**Comment by NachoPal** [comment]
> @NachoPal can you try this PR?

Replied in the PR.

> Please post more details, like genesis and transaction. I will help me a lot

I am using same genesis as here: https://github.com/AcalaNetwork/chopsticks/issues/621#issuecomment-1880710550 and the second parachain is Karura.

I had to modify Kusama config.yml in the following way
```yaml
import-storage:
  Paras:
    ParaLifecycles:
      [
        [
          [
            1000
          ],
          Parachain
        ],
        [
          [
            2000
          ],
          Parachain
        ]
      ]
```

**Comment by NachoPal** [comment]
I am still facing the same issue after you PR: https://github.com/AcalaNetwork/chopsticks/pull/635

This is the issue:
> failing when sending in AssetHubKusama with:
`polkadotXcm.Attempted {"outcome":{"Incomplete":[{"refTime":"683,414,000","proofSize":"6,196"},"Transport"]}}`
because `ingressChannel` and `egressChannel` are empty for `RelevantMessagingState` (they should be updated during the `SetValidationData()`).

How did you test HRMP messages are working? Can you share your setup?

**Comment by ermalkaleci** [comment]
chopsticks will forward any message and inject para id into validation data, but if you're starting both chains from genesis none will have para id registered. I did start acala mainnet and assethub genesis and did a xcm from acala to assethub to register para id, or override storage to make it work.

**Comment by NachoPal** [comment]
> if you're starting both chains from genesis none will have para id registered

This is exactly what I am trying to achieve. Do you mean it is not possible right now? or what is the workaround? When I override the storage in the following way:
```yaml
import-storage:
  ParachainSystem:
    RelevantMessagingState:
      dmqMqcHead: '0x0000000000000000000000000000000000000000000000000000000000000000'
      relayDispatchQueueRemainingCapacity:
        remainingCount: 8
        remainingSize: 1048576
      ingressChannels: [
        [
          2000,
          {
            maxCapacity: 1000,
            maxTotalSize: 102400,
            maxMessageSize: 102400,
            msgCount: 0,
            totalSize: 0,
            mqcHead: null
          }
        ]
      ]
      egressChannels: [
        [
          2000,
          {
            maxCapacity: 1000,
            maxTotalSize: 102400,
            maxMessageSize: 102400,
            msgCount: 0,
            totalSize: 0,
            mqcHead: null
          }
        ]
      ]
```
and try to send a XCM message to parachain `2000`, `RelevantMessagingState` is reset to:
```
{
  dmqMqcHead: "0xc41bc6b08f6edee35de2bb684a5dd197c60e58296a5c22ca3e67d74cf072499f",
  relayDispatchQueueRemainingCapacity: {
    remainingCount: 8,
    remainingSize: "1,048,576",
  },
  ingressChannels: [],
  egressChannels: []
}
```
