### ISSUE TITLE
Getting RuntimeVersionDecode error when testing with the md5 rococo parachain

### ISSUE THREAD

**Issue by sebastianmontero** [AcalaNetwork/chopsticks#663]
I'm trying to test for the md5 rococo parachain but I get the following error:

```
called `Result::unwrap()` on an `Err` value: RuntimeVersion(RuntimeVersionDecode)

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (/home/sebastian/.npm/_npx/84d26c864c64a94e/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:748:19)
    at wasm://wasm/00966b66:wasm-function[701]:0x1269bf
    at wasm://wasm/00966b66:wasm-function[866]:0x130a13
    at wasm://wasm/00966b66:wasm-function[795]:0x12b783
    at wasm://wasm/00966b66:wasm-function[105]:0xa7664
    at wasm://wasm/00966b66:wasm-function[380]:0x10eb7c
    at wasm://wasm/00966b66:wasm-function[917]:0x1312f9
    at __wbg_adapter_48 (/home/sebastian/.npm/_npx/84d26c864c64a94e/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:410:10)
    at real (/home/sebastian/.npm/_npx/84d26c864c64a94e/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:394:22)
    at node:internal/process/task_queues:140:7



node:internal/event_target:1010
  process.nextTick(() => { throw err; });
                           ^
Error [RuntimeError]: unreachable
    at wasm://wasm/00966b66:wasm-function[701]:0x126ad5
    at wasm://wasm/00966b66:wasm-function[866]:0x130a13
    at wasm://wasm/00966b66:wasm-function[795]:0x12b783
    at wasm://wasm/00966b66:wasm-function[105]:0xa7664
    at wasm://wasm/00966b66:wasm-function[380]:0x10eb7c
    at wasm://wasm/00966b66:wasm-function[917]:0x1312f9
    at __wbg_adapter_48 (/home/sebastian/.npm/_npx/84d26c864c64a94e/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:410:10)
    at real (/home/sebastian/.npm/_npx/84d26c864c64a94e/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:394:22)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```
This is the config file I'm using:

```
endpoint: wss://c1md5.hashed.live
mock-signature-host: true
block: ${env.MD5_BLOCK_NUMBER}
db: ./md5.rococo.db.sqlite
# wasm-override: ../../ComposableFi/composable/result/lib/runtime.optimized.wasm

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: "100000000000000000000000"
```

Why might this be?

**Comment by ermalkaleci** [comment]
can read runtime version from runtime.wasm. you need to use compressed one

**Comment by sebastianmontero** [comment]
@ermalkaleci so do I need to use the wasm-override parameter?

**Comment by ermalkaleci** [comment]
yes

**Comment by ermalkaleci** [comment]
to be clear. I thought you're trying custom wasm runtime. are you trying to use chopsticks for wss://c1md5.hashed.live?

**Comment by ermalkaleci** [comment]
you have the same issue. https://github.com/AcalaNetwork/chopsticks/issues/564

**Comment by sebastianmontero** [comment]
Thanks @ermalkaleci! Yes for wss://c1md5.hashed.live, but md5 is using polkadot v1.3.0, from what I understand from the issue is that they are using an old version, correct?

**Comment by ermalkaleci** [comment]
yes, there're using old version but in your case it seems smoldot can find version from your wasm runtime

**Comment by sebastianmontero** [comment]
Ok, I'll try using the branch mentioned in the issue, thanks!

**Comment by ermalkaleci** [comment]
I started debugging smoldot to see if there was any problem and turns out the your problem is `stateVersion: 5` the old version is 0 and new trie version is 1.
<img width="338" alt="Screenshot 2024-01-30 at 11 39 26 PM" src="https://github.com/AcalaNetwork/chopsticks/assets/3055344/b157c846-2690-4021-86f5-05bd2c9fbe89">

**Comment by ermalkaleci** [comment]
That means your runtime has methods unrecognized by smoldot. Try with allow-unresolved-imports: true

**Comment by sebastianmontero** [comment]
That worked, but I guess it won't work until I upgrade the on chain runtime with the correct state version, because now it runs, but when I go into polkadotjs app, it crashes and I get the RuntimeVersion(RuntimeVersionDecode) error, is this correct?

**Comment by ermalkaleci** [comment]
It should work with both wasm-override and allow-unresolved-imports.

**Comment by sebastianmontero** [comment]
It runs:
![image](https://github.com/AcalaNetwork/chopsticks/assets/13155714/1d8b5702-fec8-44b4-b3bb-a37167ecc295)

But when I go to the polkadotjsapp it throws the error:
![image](https://github.com/AcalaNetwork/chopsticks/assets/13155714/135a62e1-2c09-4fb3-bdde-f27104cdc132)

**Comment by ermalkaleci** [comment]
how do you override wasm?

**Comment by ermalkaleci** [comment]
if you upload your custom wasm with correct trie version number I can give it a try

**Comment by sebastianmontero** [comment]
This is my config file:
```
endpoint: wss://c1md5.hashed.live
mock-signature-host: true
block: ${env.MD5_BLOCK_NUMBER}
db: ./md5.rococo.db.sqlite
allow-unresolved-imports: true
wasm-override: ../hashed-substrate-parachain/target/release/wbuild/hashed-parachain-runtime/hashed_parachain_runtime.compact.compressed.wasm

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: "100000000000000000000000"
```
Here is the [wasm](https://drive.google.com/file/d/1Q8s88VmpiXJgzcCqQraRfK6XQCYgRIVA/view?usp=sharing)
Thanks!
