### ISSUE TITLE
Dry run and further inspect 

### ISSUE THREAD

**Issue by kianenigma** [AcalaNetwork/chopsticks#693]
Somewhat related to what I am hoping to be able to do in https://github.com/polkadot-js/apps/pull/10342

It would be great if I can `dry-run`, but instead of relying on the html output to inspect the outcome, do that in the PJS Apps. 

So I would imagine: 

1. Chopsticks running in one terminal, exposing the RPC
2. Chopsticks `dry-run` command in another
3. Go to Apps to see the outcome

As noted, this would all be possible from the UI once https://github.com/polkadot-js/apps/pull/10342 is done. 

I am not sure, but possible if I just run the Chopstick RPC provider, and write a few lines of PJS-API script that does `signFake` and submit an extrinsic in the normal route, it might all work? not sure.

**Comment by ermalkaleci** [comment]
Dry-run can be done completely on browser. You can have multiple chains and xcm

**Comment by qiweiii** [comment]
Don't need to start chopsticks in one terminal before doing a dry-run command, you can just dry-run an extrinsic and see results.

I think what you want is to run chopsticks in a terminal using a custom config file like this:
`npx @acala-network/chopsticks@latest -c acala.yml`

An example config file:
```yml
# acala.yml
endpoint: wss://acala-rpc-1.aca-api.network
port: 8000
mock-signature-host: true
block: '4500000'

# Add your account and tokens in import-storage section
import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5EkStBVtFxLo7E61FYNVeXMsawW6byg7QCdk42vQMxxB7Gib
        - providers: 1
          data:
            free: 1000000000000000
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Tokens:
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: AUSD
        - free: 1000000000000000
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: DOT
        - free: 1000000000000000
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: LDOT
        - free: 1000000000000000
      -
        -
          - 5EkStBVtFxLo7E61FYNVeXMsawW6byg7QCdk42vQMxxB7Gib
          - token: AUSD
        - free: 1000000000000000
```

Then go to pjs app, and set the custom endpoint `ws://localhost:8000`, click on `Switch`

<img width="311" alt="image" src="https://github.com/AcalaNetwork/chopsticks/assets/32790369/538b55d2-b4de-4883-9a36-0e86ee39b2eb">

Now you are using pjs app like normal.

---

You can also start multiple chain with xcm, using multiple config files:
`npx @acala-network/chopsticks@latest -- -- xcm -r polkadot.yml -p acala.yml hydradx.yml`

Then you can open multiple pjs app tabs and each connect to a different custom endpoint
