### ISSUE TITLE
when attempting to cross-chain $pink from Acala to Moonbeam, an error occurred.

### ISSUE THREAD

**Issue by StrawberryFlavor** [AcalaNetwork/chopsticks#712]
```
 INFO (ws): Error handling request: 'ResponseError: {"invalid":{"stale":null}}
    at /root/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/rpc/substrate/author.js:34:15
    at async processRequest (/root/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/server.js:211:30)
    at async WebSocket.<anonymous> (/root/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks/dist/cjs/server.js:273:30)'
    app: "chopsticks"
```
<img width="1001" alt="image" src="https://github.com/AcalaNetwork/chopsticks/assets/28721839/5d011efd-a6cc-4732-acf2-0a0b2b9d1b8d">

**Comment by ermalkaleci** [comment]
can you give a bit more context how to test this (setup process)?

**Comment by StrawberryFlavor** [comment]
> can you give a bit more context how to test this (setup process)?


 I'm using `npx @acala-network/chopsticks@latest xcm --relaychain=/root/configs/polkadot.yml --parachain=/root/configs/acala.yml --parachain=/root/configs/statemint.yml --parachain=/root/configs/moonbeam.yml` Then, I'm attempting to cross-chain $PINK from Acala to Moonbeam (you can see the specific transaction setup in the screenshot I provided above), but it seems Chopsticks is reporting an error message.

Here is the configuration information for my moonbeam.yml file.
```
endpoint: wss://wss.api.moonbeam.network
mock-signature-host: true
db: ./moonbeam.sqlite
block: 5804429
port: 7001

import-storage:
  System:
    Account:
      -
        -
          - "0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac"
        - data:
            free: "100000000000000000000000"
  TechCommitteeCollective:
    Members: ["0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac"]
  CouncilCollective:
    Members: ["0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac"]
  TreasuryCouncilCollective:
    Members: ["0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac"]
  AuthorFilter:
    EligibleRatio: 100
    EligibleCount: 100
```
