### ISSUE TITLE
Error: hexadecimal string doesn't start with 0x on an `archive_unstable_call`

### ISSUE THREAD

**Issue by Tbaut** [AcalaNetwork/chopsticks#915]
Hi,
It sounds like the api for archive nodes have been stabilized (although not documented).
I believe this is the reason for the following error:
```sh
[14:22:59.110] TRACE (ws): Received single request
[0]     app: "chopsticks"
[0]     req: {
[0]       "id": 13,
[0]       "jsonrpc": "2.0",
[0]       "method": "archive_unstable_call",
[0]       "params": [
[0]         "0xd828a3b9390e6335475760c4972130bbfe3f5dd2b83302ea27008321f848afe8",
[0]         "Metadata_metadata",
[0]         ""
[0]       ]
[0]     }
[0] [14:22:59.110] TRACE (ws): Received message
[0]     app: "chopsticks"
[0]     id: 13
[0]     method: "archive_unstable_call"
[0] [14:22:59.110] TRACE (rpc): Handling archive_unstable_call
[0]     app: "chopsticks"
[0] [14:22:59.110] TRACE (executor): taskRun
[0]     app: "chopsticks"
[0]     wasm: "0x52bc537646db8e0528b52ffd005874ec...f2ae6ba88b06c4ee2d381618b76ae99c"
[0]     calls: [
[0]       [
[0]         "0xd828a3b9390e6335475760c4972130bbfe3f5dd2b83302ea27008321f848afe8",
[0]         [
[0]           "Metadata_metadata"
[0]         ]
[0]       ]
[0]     ]
[0]     mockSignatureHost: true
[0]     allowUnresolvedImports: false
[0]     runtimeLogLevel: 2
[0]     storageProofSize: 0
[0] [14:22:59.149] ERROR (ws): Error handling request: 'Error: hexadecimal string doesn't start with 0x
[0]     at imports.wbg.__wbindgen_error_new (/home/thib/.npm/_npx/731e060e18c585bf/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:570:19)
[0]     at wasm://wasm/00bdbb8a:wasm-function[427]:0x1611f0
[0]     at wasm://wasm/00bdbb8a:wasm-function[276]:0x13aea9
[0]     at wasm://wasm/00bdbb8a:wasm-function[361]:0x151c4e
[0]     at wasm://wasm/00bdbb8a:wasm-function[105]:0xaf23e
[0]     at wasm://wasm/00bdbb8a:wasm-function[497]:0x16e5c7
[0]     at wasm://wasm/00bdbb8a:wasm-function[1491]:0x1c326c
[0]     at __wbg_adapter_48 (/home/thib/.npm/_npx/731e060e18c585bf/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:419:10)
[0]     at real (/home/thib/.npm/_npx/731e060e18c585bf/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:401:22)
[0]     at node:internal/process/task_queues:151:7'
[0]     app: "chopsticks"
```

With the following config:
```yml
endpoint: wss://rpc-kusama.luckyfriday.io
mock-signature-host: true
block: 28000000
db: ./db.sqlite
# wasm-override: staging_kusama_runtime.wasm
runtime-log-level: 2

import-storage:
  System:
    Account:
      - - - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: '10000000000000000000'
      - - - JEqfw2FPda5eycsqqXN2Ay67eEh5R85aSHcArs3XdUYjj5H
        - providers: 1
          data:
            free: '10000000000000000000'
      - - - JF3RaX21TrQuPrRbEV7i1iT5QXNQZBN6qvKx3iZN8CEN9bB
        - providers: 1
          data:
            free: '10000000000000000000'
      - - - HxehWqUZGorCrahv3PiWWqdcFNBG9oQhZ2ft5VXueWaSBEs
        - providers: 1
          data:
            free: '10000000000000000000'
  FellowshipCollective:
    $removePrefix:
      - IdToIndex
      - IndexToId
      - MemberCount
      - Members
    IdToIndex:
      - [[0, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
      - [[1, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
      - [[2, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
      - [[3, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
      - [[4, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
      - [[5, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
      - [[6, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
      - [[7, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], 0]
    IndexToId:
      - [[0, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
      - [[1, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
      - [[2, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
      - [[3, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
      - [[4, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
      - [[5, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
      - [[6, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
      - [[7, 0], 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
    MemberCount:
      - [[0], 1]
      - [[1], 1]
      - [[2], 1]
      - [[3], 1]
      - [[4], 1]
      - [[5], 1]
      - [[6], 1]
      - [[7], 1]
    Members:
      - [[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], rank: 7]
    Voting: []
  ParasDisputes:
    # $removePrefix: ['disputes'] # those can makes block building super slow

```
Any guidance for resolving the issue would be appreciated.
